### ISSUE TITLE
New release: 4.0.2

### ISSUE THREAD

**Issue by farkasseb** [MakeAWishFoundation/SwiftyMockyCLI#14]
Thank you for merging #13! Could you please also merge `develop` to `master` and create the `4.0.2` release (tag)?

This would also fix #12 if I'm not mistaken.

**Comment by farkasseb** [comment]
Gentle ping @g-amichnia, how can I help to make this fix released?

**Comment by g-amichnia** [comment]
@farkasseb Will look into that today, thanks for ping.

**Comment by g-amichnia** [comment]
@farkasseb there is one more thing I wanted to look into, so it got delayed one day. Stay tuned.

**Comment by g-amichnia** [comment]
Just one remark - Mockfile allows to specify custom Sourcery command if needed, just in case of this happening again in the future (https://cdn.rawgit.com/MakeAWishFoundation/SwiftyMocky/4.0.1/docs/mockfile.html).

We will always be a bit behind, so if anybody can't wait for new SwiftyMockyCLI version, it can be workaround by installing newer Sourcery manually and adding 'sourceryCommand' in Mockfile.

**Comment by g-amichnia** [comment]
@farkasseb aaaand its done, Version 4.0.2 is there.

**Comment by farkasseb** [comment]
Thank you very much! :) Good idea about specifying a custom Sourcery. However, I might argue that the `Mockfile` might also have an option to define the *version* of Sourcery that will be used with `mint`. The fallback version would always be hardcoded, but this way `mint` could be updated without a new release. What do you think?

```
sourceryVersion:
    - 1.0.3
```

**Comment by g-amichnia** [comment]
@farkasseb I did some additional tests and Sourcery 1.0.2 introduced some new issues to mock generation. Mostly to elements that are very rare, like unnamed parameters, but it can break some generated mocks. I will push 4.0.3 as soon as I finish updating main SwiftyMocky library.

As for the question, I will add this parameter to new mockfile. That would lower the entry point when somebody needs to test with other version.

**Comment by farkasseb** [comment]
Thanks! Let me know if I can help!
